Hw02
vova-rsk/goit-nodejs-hw-rest-api pull request #1
Opened 2021-11-19 13:20 UTC by vova-rsk

Привет! Просьба максимально критично сделать ревью..)

2021-11-20 13:49 UTC, KirillKulakow commented on .env
> +PORT=8080
такой файл как .env обычно добавляют в .gitignore

2021-11-20 13:52 UTC, KirillKulakow commented on utils/validation.js
> +const Joi = require('joi')
было бы неплохо сделать эту валидацию как миддлвару

2021-11-20 13:57 UTC, KirillKulakow approved these changes, later dismissed

2021-11-20 14:05 UTC, KirillKulakow commented on routes/api/contacts.js
> +router.patch('/:contactId', patchContact)
согласно задания метод patch отсутствует

2021-11-20 14:13 UTC, KirillKulakow commented on utils/validation.js
> +const Joi = require('joi')
как по мне 2/3 кода который здесь записан - лишний
зачем разделять логику по структуре и по валидации самих полей? за тебя все делает пакет JOI
зачем  функция contactToPatchValidation - если такие HTTP методы подразумевают в себе что body должен состоять из всех сущностей изменяемого объекта
То есть - если у тебя есть контакт { name: "traTaTa", phone: "333-23-23", email: "lasper@test.net"  } и ты хочешь поменять через put только phone - тогда boy должен быть прописан так: 
{ name: "traTaTa", phone: "363-41-90", email: "lasper@test.net"  }

2021-11-20 14:13 UTC, KirillKulakow commented on utils/validation.js
> +const valuesSchema = Joi.object({
итог две схемы совместить!

2021-11-20 14:13 UTC, KirillKulakow commented on utils/validation.js
> +const contactToPatchValidation = contact => {
эта функция лишняя

2021-11-20 14:14 UTC, KirillKulakow requested changes
Need fix

2021-11-20 20:42 UTC, vova-rsk commented on .env
> +PORT=8080
исправил

2021-11-20 20:42 UTC, vova-rsk commented on utils/validation.js
> +const Joi = require('joi')
переделал

2021-11-20 20:45 UTC, vova-rsk commented on routes/api/contacts.js
> +router.patch('/:contactId', patchContact)
пофиксил, изначально так в шаблоне было, потому подумал что в ТЗ put - это опечатка, т.к. опечатки в ТЗ на реакте уже встречались..

2021-11-20 20:45 UTC, vova-rsk commented on utils/validation.js
> +const valuesSchema = Joi.object({
переделал

2021-11-20 20:45 UTC, vova-rsk commented on utils/validation.js
> +const contactToPatchValidation = contact => {
переделал

2021-11-21 08:12 UTC, KirillKulakow approved these changes

2021-11-21 09:13 UTC, merged