refactoring & add new feature
vova-rsk/goit-nodejs-hw-rest-api pull request #3
Opened 2021-12-03 15:04 UTC by vova-rsk

Привет!) Сделай пжл код-ревью..

2021-12-04 17:36 UTC, KirillKulakow commented on controllers/contacts/getContacts.js
> +  Contact.paginate({ owner, favorite: { $in: favorite } }, options, function (err, result) {
данный вариант точно работает `{ $in: favorite }` если в запрос поставить favorite true?

2021-12-04 17:43 UTC, KirillKulakow commented on middlewares/auth/auth.js
> +    const { authorization } = req.headers
проверяй есть ли authorization в headers

2021-12-04 17:45 UTC, KirillKulakow requested changes
Need so fix

2021-12-04 17:47 UTC, vova-rsk commented on controllers/contacts/getContacts.js
> +  Contact.paginate({ owner, favorite: { $in: favorite } }, options, function (err, result) {
видимо я что-то сломал перед пулл-риквестом. до этого точно работало. сейчас гляну где я что сломал...

2021-12-04 19:05 UTC, vova-rsk commented on middlewares/auth/auth.js
> +    const { authorization } = req.headers
исправил

2021-12-05 17:17 UTC, KirillKulakow approved these changes

2021-12-05 17:30 UTC, merged