Hw05 avatars
vova-rsk/goit-nodejs-hw-rest-api pull request #4
Opened 2021-12-10 17:41 UTC by vova-rsk

привет! Сделай пжл код ревью...   С удалением старого файла аватарки, при отличии расширения у нового, не заморачивался, т.к. в условии дз об этом не уточнялось. Если таки надо это сделать - укажешь в доработке...

2021-12-10 19:49 UTC, KirillKulakow commented on controllers/users/loginUser.js
> +    .findByIdAndUpdate(id, { token }, { new: true })
нашел непонятную реализацию которую в прошлый раз не доглядел
а почему логинизация идет исходя из ид и имейла?

2021-12-10 19:53 UTC, KirillKulakow commented on controllers/users/updateUserAvatar.js
> +      .findByIdAndUpdate(id, { avatarURL: path.join('avatars', newUniqueName) }, { new: true })
здесь нужно записывать полный путь учитывая твой хостнейм

2021-12-10 20:00 UTC, KirillKulakow requested changes
Need some fix

2021-12-11 13:15 UTC, vova-rsk commented on controllers/users/loginUser.js
> +    .findByIdAndUpdate(id, { token }, { new: true })
отрефакторил..  просто в прошлый раз я часть логики по валидации, проверке наличия указанного пользователя и валидного пароля вынес в мидлвар, который при успешной проверке возвращал уже в сам контроллер id пользователя и мейл. А сам контроллер уже просто создавал токен и все прочее.

2021-12-11 13:16 UTC, vova-rsk commented on controllers/users/updateUserAvatar.js
> +      .findByIdAndUpdate(id, { avatarURL: path.join('avatars', newUniqueName) }, { new: true })
пофиксил

2021-12-12 14:43 UTC, KirillKulakow approved these changes

2021-12-12 15:20 UTC, merged